modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/CodeOfArdonia/DefaultHotkeys/issues"
license = "LGPL-3.0"

[[mods]]
modId = "defaulted_hotkeys"
version = "${version}"
displayName = "Defaulted Hotkeys"
authors = "IAFEnvoy"
description = '''
Change any default keybindings.
'''
logoFile = "logo.png"

[[dependencies.defaulted_hotkeys]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.defaulted_hotkeys]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"
