modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CodeOfArdonia/DefaultHotkeys/issues"
license = "LGPL-3.0"

[[mods]]
modId = "defaulted_hotkeys"
version = "${version}"
displayName = "Defaulted Hotkeys"
authors = "IAFEnvoy"
description = '''
Change any default keybindings.
'''
logoFile = "logo.png"

[[dependencies.defaulted_hotkeys]]
modId = "neoforge"
type="required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.defaulted_hotkeys]]
modId = "minecraft"
type="required"
versionRange = "[1.20.4,1.20.5)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "defaulted_hotkeys.mixins.json"